<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>

<div id="trainer-container" data-mage-init='{ "Tsum_TrainBrain/js/math_exercise": {"test":true} }'>
    <div>
        Here is the clock:<span id="clock">0</span>s
    </div>
    <div>
        <button id="btn_start">Start</button>
        <button id="btn_stop">Pause</button>
    </div>
    <br/>
    <br/>
</div>
