<?php
// @codingStandardsIgnoreFile
/** @var Magento\Framework\View\Element\Template $block */

?>
    <select id="tsum-knowledge-multiselect" name="multiselect-field" multiple="multiple">

    </select>

<!-- Description Input Field -->
<input type="text" name="description" class="description-field" placeholder="Knowledge Description">

<!-- Add Button -->
<button type="button" class="add-button" disabled>Add</button>

<!-- Initialize the Widget -->
<!--<script>-->
<!--    require([-->
<!--        'jquery',-->
<!--        'Tsum_Knowledge/js/creator'-->
<!--    ], function ($) {-->
<!--        $('#tsum-knowledge-multiselect').knowledgeCreator({-->
<!--            // Options for the widget, including ajaxUrl-->
<!--        });-->
<!--    });-->
<!--</script>-->

<script type="text/x-magento-init">
    {
        "#tsum-knowledge-multiselect": {
            "Tsum_Knowledge/js/creator": {}
        }
    }
</script>
